### ISSUE TITLE
virustotal_python requirement error

### ISSUE THREAD

**Issue by 0xVIC** [al0ne/Vxscan#15]
Fresh install, uninstall and installing again, still have the same error.

Traceback (most recent call last):
  File "Vxscan.py", line 30, in <module>
    from lib.common import start, bcolors
  File "/opt/Vxscan/lib/common.py", line 13, in <module>
    from virustotal_python import Virustotal
  File "/usr/local/lib/python3.5/dist-packages/virustotal_python/__init__.py", line 1, in <module>
    from virustotal_python.virustotal import Virustotal
  File "/usr/local/lib/python3.5/dist-packages/virustotal_python/virustotal.py", line 27
    print(f"Failed to import required modules: {err}")

**Comment by al0ne** [comment]
Requires Python version 3.6 or higher
