### ISSUE TITLE
SyntaxError: invalid syntax

### ISSUE THREAD

**Issue by nauliajati** [al0ne/Vxscan#16]
Hi, my system using Ubuntu 16.04 LTS, and i'm getting this problem when i'm running this command > "python3 Vxscan.py -h"
can u guide me please how to solve this issue? Thanks.

Traceback (most recent call last):
  File "Vxscan.py", line 31, in <module>
    from lib.common import start, bcolors
  File "/home/xxx/vxscan/Vxscan/lib/common.py", line 13, in <module>
    from virustotal_python import Virustotal
  File "/home/xxx/.local/lib/python3.5/site-packages/virustotal_python/__init__.py", line 1, in <module>
    from virustotal_python.virustotal import Virustotal
  File "/home/xxx/.local/lib/python3.5/site-packages/virustotal_python/virustotal.py", line 27
    print(f"Failed to import required modules: {err}")
                                                    ^

**Comment by al0ne** [comment]
Requires Python version 3.6 or higher
