### ISSUE TITLE
使用绝对路径执行命令时，会出现以下错误

### ISSUE THREAD

**Issue by handbye** [al0ne/Vxscan#29]
python3 /Users/admin/Documents/hack/SRC/src/lib/Vxscan/Vxscan.py -u darkless.cn -s vxscan

```
ERROR:root:[Errno 2] No such file or directory: 'data/apps.json'
Traceback (most recent call last):
  File "/Users/admin/Documents/hack/SRC/src/lib/Vxscan/lib/web_info.py", line 28, in web_info
    webinfo = WebPage(r.url, r.text, r.headers).info()
  File "/Users/admin/Documents/hack/SRC/src/lib/Vxscan/plugins/PassiveReconnaissance/wappalyzer.py", line 53, in __init__
    wappalyzer = Wappalyzer()
  File "/Users/admin/Documents/hack/SRC/src/lib/Vxscan/plugins/PassiveReconnaissance/wappalyzer.py", line 130, in __init__
    with open("data/apps.json", 'rb') as fd:
FileNotFoundError: [Errno 2] No such file or directory: 'data/apps.json'
ERROR:root:[Errno 2] No such file or directory: 'report/report.htm'
Traceback (most recent call last):
  File "/Users/admin/Documents/hack/SRC/src/lib/Vxscan/Vxscan.py", line 28, in <module>
    options()
  File "/Users/admin/Documents/hack/SRC/src/lib/Vxscan/lib/options.py", line 65, in options
    gener()
  File "/Users/admin/Documents/hack/SRC/src/lib/Vxscan/report.py", line 353, in gener
    with open('report/report.htm', 'r', encoding='utf-8') as f, open(name, 'w') as f1:
FileNotFoundError: [Errno 2] No such file or directory: 'report/report.htm'
```

**Comment by handbye** [comment]
已解决
