### ISSUE TITLE
ModuleNotFoundError: No module named '_cffi_backend'

### ISSUE THREAD

**Issue by Yohansun** [al0ne/Vxscan#37]
Traceback (most recent call last):
  File "Vxscan.py", line 11, in <module>
    from lib.options import options
  File "/var/ios/Vxscan-master/lib/options.py", line 8, in <module>
    from lib.common import start
  File "/var/ios/Vxscan-master/lib/common.py", line 10, in <module>
    from lib.verify import verify_https
  File "/var/ios/Vxscan-master/lib/verify.py", line 9, in <module>
    from lib.Requests import Requests
  File "/var/ios/Vxscan-master/lib/Requests.py", line 10, in <module>
    import OpenSSL
  File "/usr/lib/python3/dist-packages/OpenSSL/__init__.py", line 8, in <module>
    from OpenSSL import crypto, SSL
  File "/usr/lib/python3/dist-packages/OpenSSL/crypto.py", line 12, in <module>
    from cryptography import x509
  File "/usr/lib/python3/dist-packages/cryptography/x509/__init__.py", line 8, in <module>
    from cryptography.x509.base import (
  File "/usr/lib/python3/dist-packages/cryptography/x509/base.py", line 16, in <module>
    from cryptography.x509.extensions import Extension, ExtensionType
  File "/usr/lib/python3/dist-packages/cryptography/x509/extensions.py", line 18, in <module>
    from cryptography.hazmat.primitives import constant_time, serialization
  File "/usr/lib/python3/dist-packages/cryptography/hazmat/primitives/constant_time.py", line 9, in <module>
    from cryptography.hazmat.bindings._constant_time import lib
ModuleNotFoundError: No module named '_cffi_backend'

报错如上

**Comment by Yohansun** [comment]
pip3 install cffi
